global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'coopcredit-monitor'

scrape_configs:
  - job_name: 'coopcredit-app'
    static_configs:
      - targets: ['coopcredit-app:8081']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'risk-service'
    static_configs:
      - targets: ['risk-service:8082']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
